- name: Install Nginx 
  yum:
    name=nginx
    state=latest
 systemd:
    name: nginx
    enabled: yes
- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

